"""The lab half against the theory half: `fit_branch` must recover
the threshold and the exponent of branches GENERATED by the exact
parametric solution (conservative kernel beta = 1, algebraic tail
s = 2.5 -> beta = 2/3), noiseless and under seeded noise within its
own reported error bars; `kernel_tail_from_beta` inverts the exact
dictionary and refuses at the unidentifiable beta = 1/2 class; the
planning closed form is held against seeded simulation and its
inversion is two-sided; and every refusal fires with its reason."""
import numpy as np
import pytest

from lockkernel import (beta_relative_sigma, fit_branch,
                        kernel_tail_from_beta, points_for_beta)
from lockkernel.kernels import conservative, power_tail, predicted_beta
from lockkernel.lineshapes import lorentzian
from lockkernel.parametric import sweep, threshold

REF = "generated by lockkernel.parametric.sweep (exact branch)"


def _branch(kernel, exponents):
    line = lorentzian()
    pts = sweep(line, kernel, exponents)
    chi = np.array([float(p[0]) for p in pts])
    r = np.array([float(p[1]) for p in pts])
    return line, chi, r


def test_fit_recovers_conservative_branch():
    """Conservative kernel: beta = 1 and chiN_c = 1/(p(0) pi),
    both recovered from branch points alone."""
    kern = conservative()
    line, chi, r = _branch(kern, np.linspace(-4.3, -2.0, 12))
    fit = fit_branch(chi, r, REF)
    chi_c_exact = float(threshold(line, kern))
    assert abs(fit.beta - 1.0) < 0.02
    assert abs(fit.chi_c / chi_c_exact - 1.0) < 1e-3
    assert fit.n_points == 12
    assert fit.residual_rms_log < 0.02


def test_fit_recovers_power_tail_branch():
    """W ~ |u|^-2.5: beta = 1/(s-1) = 2/3, and the tail exponent
    read back off the fitted beta returns s = 2.5."""
    s_true = 2.5
    kern = power_tail(s_true)
    line, chi, r = _branch(kern, np.linspace(-5.0, -2.4, 12))
    fit = fit_branch(chi, r, REF)
    assert abs(fit.beta - predicted_beta(s_true)) < 0.02
    assert abs(fit.chi_c / float(threshold(line, kern)) - 1.0) < 1e-3
    s_est, s_sig = kernel_tail_from_beta(fit.beta,
                                         max(fit.sigma_beta, 0.01))
    assert abs(s_est - s_true) < 0.1


def test_noisy_fit_within_its_own_error_bars():
    kern = conservative()
    _, chi, r = _branch(kern, np.linspace(-4.3, -1.8, 14))
    rng = np.random.default_rng(20260918)
    sigma_rel = 0.02
    r_noisy = r * np.exp(rng.normal(0.0, sigma_rel, r.size))
    fit = fit_branch(chi, r_noisy, REF, sigma_r=sigma_rel * r_noisy)
    assert abs(fit.beta - 1.0) < 4.0 * fit.sigma_beta
    assert 0.9 < fit.beta < 1.1
    assert fit.sigma_beta < 0.05


def test_tail_dictionary_and_refusals():
    s, sig = kernel_tail_from_beta(1.0, 0.02)
    assert abs(s - 2.0) < 1e-12 and abs(sig - 0.02) < 1e-12
    with pytest.raises(ValueError, match="CLASS"):
        kernel_tail_from_beta(0.52, 0.02)
    with pytest.raises(ValueError, match="below"):
        kernel_tail_from_beta(0.3, 0.01)
    with pytest.raises(ValueError, match="positive"):
        kernel_tail_from_beta(-1.0)


def test_plan_closed_form_vs_seeded_simulation():
    n, dec, slog = 12, 2.0, 0.05
    pred = beta_relative_sigma(n, dec, slog)
    rng = np.random.default_rng(7)
    x = np.linspace(0.0, dec * np.log(10.0), n)
    xc = x - x.mean()
    trials = 6000
    y = 0.66 * x + rng.normal(0.0, slog, size=(trials, n))
    slopes = (y @ xc) / (xc @ xc)
    emp = slopes.std(ddof=1)
    assert abs(emp / pred - 1.0) < 0.05


def test_points_inversion_two_sided():
    tgt = 0.01
    n, achieved = points_for_beta(tgt, 2.0, 0.05)
    assert achieved <= tgt
    assert beta_relative_sigma(n - 1, 2.0, 0.05) > tgt


def test_fit_refusals():
    kern = conservative()
    _, chi, r = _branch(kern, np.linspace(-4.3, -2.0, 12))
    with pytest.raises(ValueError, match="reference"):
        fit_branch(chi, r, "x")
    with pytest.raises(ValueError, match=">= 6"):
        fit_branch(chi[:4], r[:4], REF)
    with pytest.raises(ValueError, match="strictly"):
        fit_branch(chi[::-1], r[::-1], REF)
    with pytest.raises(ValueError, match="no exponent information"):
        fit_branch(chi, r - r[0], REF)
    # a span of eps too short to separate exponent from amplitude
    _, chi2, r2 = _branch(kern, np.linspace(-2.6, -2.0, 8))
    with pytest.raises(ValueError, match="decades"):
        fit_branch(chi2, r2, REF)
    # first point essentially AT the fitted threshold
    chi_c = 0.5
    eps = np.geomspace(1e-10, 1e-2, 10)
    with pytest.raises(ValueError, match="smallest measured"):
        fit_branch(chi_c * (1.0 + eps), eps ** 1.0, REF)


def test_metadata_and_no_matplotlib():
    import subprocess
    import sys
    out = subprocess.run(
        [sys.executable, "-c",
         "import sys; import lockkernel; "
         "print(lockkernel.__version__); "
         "print('matplotlib' in sys.modules)"],
        capture_output=True, text=True, check=True)
    version, has_mpl = out.stdout.split()
    assert version == "1.1.0"
    assert has_mpl == "False"
